### ISSUE TITLE
Twitch.Tv

### ISSUE THREAD

**Issue by CatIsHappy** [ZionDevelopers/playx#75]
Screen turns black when we try to do a twitch livestream.

**Comment by juliocoliveira** [comment]
Try to do or try to play?
Because playx do not support twitch broadcast (Upload)

**Comment by CatIsHappy** [comment]
Tried to play a twitch broadcast

**Comment by CatIsHappy** [comment]
Any other thing works like Youtube or Soundcloud but twitch just goes black

**Comment by juliocoliveira** [comment]
i need more details then that, like URL, errors if any.

**Comment by CatIsHappy** [comment]
No twitch broadcast plays at all and there are no errors at all

**Comment by juliocoliveira** [comment]
i need the URL....

**Comment by CatIsHappy** [comment]
www.twitch.tv/catishappy its my broadcast

**Comment by CatIsHappy** [comment]
It works in the browser but not the game. Have even tried multiplayer but doesnt work

**Comment by CatIsHappy** [comment]
No broadcasts work for me at all
Not even mine

**Comment by CatIsHappy** [comment]
Also if it helps, I played the broadcast on my server and nobody else could see it either.

**Comment by juliocoliveira** [comment]
I founded why, Twitch changed the flash URL.
I'll publish the new fix in a few minutes.

**Comment by CatIsHappy** [comment]
Oh man thats great. Dude, does that mean I have to update playx on my server also?

**Comment by juliocoliveira** [comment]
of course

**Comment by juliocoliveira** [comment]
just wait util i push the update to workshop and then you just need restart the server (If you are using workshop)

**Comment by CatIsHappy** [comment]
Give me a heads up when so I can download it and extract to my server

**Comment by juliocoliveira** [comment]
Done, Updated at Github and Workshop.

**Comment by CatIsHappy** [comment]
Thanks man!

**Comment by CatIsHappy** [comment]
Okay so I downloaded it and extracted it to my server but we still get the glitches.

**Comment by juliocoliveira** [comment]
Not is really fixed download again

**Comment by CatIsHappy** [comment]
Works great, thanks!
